- id: 1
  author: Lulu
  date: 2017-02-18 02:15:01
  content: |
    Bonnet merci pour votre article.. cependant comment faire pour communiquer avec le player de la livebox et d'autres p√©riph√©riques car il y a un prie tre les adresse IP qui ne sont pas sur la m√™me plage!

    Merci

- id: 2
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2017-02-21 18:05:55
  content: |
    Bonjour, je ne suis pas s√ªr d‚Äôavoir compris votre question, pouvez-vous d√©tailler ? Merci üôÇ

- id: 3
  author: Arnaud
  date: 2017-02-28 10:45:59
  content: |
    Bonjour Guillaume, merci pour cet article qui est tr√®s bien expliqu√©. Juste une petite question concernant le player TV Orange. Ou faut il le brancher pour conserver le flux IPTV et VOD. Sur un port LAN du rt1900ac ou sur un port LAN de la LiveBox ?

    Merci de ton aide.

- id: 4
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2017-03-08 23:33:27
  content: |
    Merci pour ton retour :) J'ai essay√© qu'une seule fois et de m√©moire √ßa marche tr√®s bien directement sur le Synology. A tester pour √™tre s√ªr, si tu peux nous confirmer √ßa, ce serait top !

- id: 5
  author: Paul
  date: 2017-03-08 18:00:43
  content: |
    Bonjour Guillaume,

    Merci et bravo pour la qualit√© de ton article ! Apr√®s plusieurs recherches, tu es le seul √† avoir √©crit un article sur le sujet.
    J'avais une petite question, sachant que le trafic entrant est redirig√© de la Livebox vers le RT1900ac, qu'en est-il du trafic sortant ?
    Dois-je faire mes r√®gles NAT/PAT sur le routeur synology, la livebox, ou les deux ?

    As-tu rencontr√© des soucis particuliers ?

    Merci de ton retour et encore bravo pour ton travail !

- id: 6
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2017-03-08 23:31:02
  content: |
    Bonjour Paul,

    Merci pour ton retour ! Alors pour ce qui est des flux sortants le principe est exactement le m√™me, une fois ton routeur dans la DMZ, tu n'as plus rien √† faire, tous les √©changes qui tu fais via ton Synology seront redirig√©s sur la livebox puis vers internet. Aucune r√®gle NAT/PAT √† configurer et je n'ai, avec cette configuration, eu aucun souci.

    Si tu as d'autres questions n'h√©site pas :)

- id: 7
  author: Jordan
  date: 2017-03-10 23:08:14
  content: |
    Rencontres-tu une baisse de d√©bit.

    Car moi ayant presque 1Gbits de bande passante, je passe √† 200Mbits en gardant ma LiveBox.

- id: 8
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2017-03-11 13:00:06
  content: |
    Bonjour, les speedtests en √©tant sur la Livebox directement ou en passant par le Synology sont significativement les m√™mes donc aucun probl√®me pour moi √† ce niveau l√†.

- id: 9
  author: Paul
  date: 2017-03-15 17:20:20
  content: |
    Parfait ! Merci beaucoup pour ton retour.

    As-tu mis en place le LoadBalancing + Failover ?

    Je l'installe ce soir, je te ferais un retour apr√®s quelques jours d'utilisation si tu veux. :)

    Bonne journ√©e !

- id: 10
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2017-03-18 14:36:48
  content: |
    Aucun des deux, je n'en ai pas le besoin. Je suis tout seul (ou presque) √† me servir de mon r√©seau et du NAS. Je sature ma connexion bien trop occasionnellement pour mettre le LoadBalancing en place.

    Et pour le Failover, je n'ai qu'une connexion qui ne coupe que tr√®s rarement (voire jamais) et au pire, je relance la Livebox et c'est reparti. :)

    Ah oui ce serait top ! Avec plaisir, merci √† toi.

- id: 11
  author: trotroyanas
  author-url: http://www.deco-recup.com
  date: 2017-03-27 22:33:34
  content: |
    Bonsoir Guillaume,

    Merci de cet article je suis exactement dans cette configuration.
    Seulement apr√®s avoir fait tout ce que tu as dit, Routeur Syno dans la DMZ de la LiveBox, ajout de r√®gles de transfert de ports du router vers mon nas, rien n'y fait, de l'ext√©rieur c'est tjrs choux blanc.
    Chose √©trange il me change bien mon adresse en https ? 8000-> vers 8001 et 5000 -> 5001 pour mon nas mais rien derriere une page d'erreur pour ces 2, et pour mon sftp j'ai le droit √† un message "le service que vous demandez ne repond pas.

    Veuillez contacter votre service client" je sais meme pas d'ou il sort ce message.. test√© de mon tel en 4g
    Une id√©e ?

    Merci d'avance
    cH.

- id: 12
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2017-04-07 17:42:01
  content: |
    Salut, tu as essay√© en acc√®s direct pour savoir si le probl√®me venait vraiment de ta configuration ? :)

- id: 13
  author: Guy
  date: 2017-04-06 19:39:54
  content: |
    Bonjour Guillaume,

    Merci pour votre article que j'ai suivi pour configurer mon routeur plac√© derriere une LiveBox 4
    Tout fonctionne (j'ai de nombreux mat√©riels en c√¢bl√©s et en Wifi), √† l'exception de la TV Orange sur la Livebox 4 Player
    Comment cela se fait il ?
    J'avais entendu parler de Vlan/Muxid/ 835 et (838 √† 841) √† configurer. Comment et ou les configurer ?

    Merci d'avance

    Cordialement

    Guy

- id: 14
  author: Simon
  date: 2017-07-07 14:53:50
  content: |
    Hello,

    J'ai trouv√© ton article en tentant de trouver sur internet la solution √† mon probl√®me. Pour ma part, j'ai bien fais la m√™me chose que ce que tu indiques, mais le soucis que je rencontre c'est qu'en local le loopback ne fonctionne pas.

    Pour √™tre plus pr√©cis, derri√®re mon Syno RT j'ai un NAS Syno et j'ai mon service de DDNS qui est connect√© √† OVH (autant sur le RT que sur le NAS). Autant en 4g j'ai acc√®s au NAS autant en local il n'y arrive pas (cf d√©lai trop long...).

    Une id√©e ?

    Merci √† toi

- id: 15
  author: Geoffrey
  date: 2017-10-05 17:06:00
  content: |
    Bonjour Guillaume,

    Avant toute chose, je tenais √† vous remercier pour votre tutoriel sur l‚Äôinstallation d‚Äôun routeur RT1900AC en DMZ sur une Livebox !

    Merci, car il est en effet tr√®s rare de trouver des tutoriels complets comme le v√¥tre. :)

    Je me permets de vous contacter, pour avoir une information compl√©mentaire qui ne figure pas dans votre tutoriel.

    Vous indiquez, dans la partie ¬´ Configuration du routeur RT1900AC ¬ª,  je cite : ¬´ Dans l‚Äôonglet Internet > Connection pensez bien √† mettre le Set as default Gateway ¬ª

    Je ne comprend pas de quoi s‚Äôagit-il ?

    Pour information, je compte effectu√© la m√™me configuration sur une Bbox :

    IP WAN     |     Bbox  | IP Lan                   -> DMZ sur          IP WAN            |   RT1900AC   |  IP Lan

    5.xx.xxx.xxx/32   |   192.168.1.1/24                         192.168.1.2/24   |                      | 192.168.2.1/24


    Je pense qu‚Äôil faut indiquer ¬´ Type de connexion ¬ª en Manuel, mais je n‚Äôarrive pas √† voir quoi renseigner √† la suite de ceci :

    Adresse IP  :  Wan ext√©rieur ? LAN Bbox ?
    Passerelle : Lan Bbox ?


    Je ne poss√®de pas encore le routeur, mais √ßa ne saurait tarder, aussi j‚Äôanticipe sur ces questions qui vont se poser pour moi tr√®s rapidement‚Ä¶

    En vous remerciant sinc√®rement par avance du tremps consacr√© √† r√©pondre √† cette interrogation.

    Bien cordialement.

    Geoffrey

- id: 16
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2017-10-07 13:55:00
  content: |
    Bonjour Geoffrey,

    Tout d'abord, merci pour tes compliments et ta question, √ßa fait super plaisir.

    Pour r√©pondre √† ta question, le `Set as default Gateway` permet de dire aux √©l√©ments du r√©seau local que c'est par cette adresse (celle du routeur) qu'ils doivent envoyer leurs paquets pour acc√©der au r√©seau ext√©rieur et inversement si les paquets viennent de l'ext√©rieur. Sans √ßa, les clients de ton r√©seau local pourrons communiquer entre eux, mais pas vers l'ext√©rieur.

    Pour ta configuration, il faut distinguer deux choses, ton interface primaire et ton ip locale. Ton interface primaire doit √™tre l'adresse que tu as d√©finie sur ta livebox (dans ton cas `192.168.1.2`) et ta Gateway doit √™tre `192.168.1.1` (ta livebox). Et pour ton ip locale tu peux mettre ce que tu veux, mais dans ton exemple c'est `192.168.2.1`.

    Je vais voir si j'ai le temps de faire une modification sur l'article pour expliquer ce point.

    En esp√©rant avoir r√©pondu √† ta question :)

- id: 17
  author: Olivier
  date: 2017-10-26 09:20:01
  content: |
    Merci pour ton tuto, il m'a bien servi pour connecter mon RT1900 sur ma livebox zen. J'ai pu le mettre √† jour et m'apercevoir que SRM a bien √©volu√©.

- id: 18
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2017-11-03 20:54:00
  content: |
    Merci Olivier pour ton commentaire. Oui SRM et DSM √©voluent tr√®s vite en restant tr√®s stable c'est super agr√©able √† l'usage !

- id: 19
  author: Pilou
  date: 2017-11-27 11:00:46
  content: |
    Bonjour Guillaume, merci pour le tuto tr√®s complet.

    Je suis int√©ress√© par ce Routeur, mais une question reste ouverte pour moi.

    Je souhaiterais l'installer dans le cadre d'un Gite, et donc n'ouvrir que le r√©seau invit√© au client.

    Est-ce que celui-ci est brid√©?

    J'aimerais interdire l'acc√®s au P2P (Hadopi), aux sites illictes (genre p√©do-pornographie), mais laisser quand m√™me certains acc√®s (Steam par exemple).

    Est-ce qu'il le permet?

    Enfin derni√®re question: Si jamais un client contourne les protections, est-ce qu'il y a un journal de connexion (moins consommateur de bande passante que le CTF).

    Merci d'avance pour ton retour.

- id: 20
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2017-11-27 20:00:00
  content: |
    Bonjour Pilou merci pour ton retour !

    Alors, je viens de faire le test sur SRM (1.1.5-6542 Update 4), la seule option que j'ai trouv√© par rapport au r√©seau invit√© √† ce niveau-l√† c'est de l'isoler du r√©seau principal...
    Je crois que ce n'est pas encore possible sur SRM, mais je sais que pfSense le permet, en revanche on est √† des ann√©es-lumi√®re de la simplicit√© et de l'ergonomie de SRM en terme de mise en place.

    Par contre, tu peux mettre des filtres sur certaines cat√©gories de sites ou service par d√©faut sur tous les appareils, mais le couper pour certains (les tiens). Tu peux aussi filtrer les sites par url. Je m'en sers personnellement pour bloquer la publicit√© et le phishing par exemple. Tu peux trouver plus d'infos ici : [https://www.synology.com/en-us/knowledgebase/SRM/help/SRM/RouterApp/parentalcontrol_keyword](https://www.synology.com/en-us/knowledgebase/SRM/help/SRM/RouterApp/parentalcontrol_keyword)

    Pour la seconde question, √† ma connaissance tu ne pourras pas avoir un journal de connexion sans CTF, tu pourras avoir un "top" des sites visit√©s, mais pas historis√©s et group√©s par devices.

    J'esp√®re avoir r√©pondu √† la question !

    Merci √† toi.

- id: 21
  author: Pilou
  date: 2017-11-28 09:27:19
  content: |
    Bonjour Guillaume,

    √áa me semble pas mal ces cat√©gories, ainsi que la possibilit√© d'ajouter manuellement des URL.

    De ton point de vue, le filtrage fishing (difficile √† quantifier) et advertising sont-ils efficaces?

    En ce qui concerne le logging du traffic, j'ai vu sur ton tweet que pour quantifier les 2 vitesses, tu activais les 2 options ("save visited web pages", "enable detection application").

    De ce que je comprends de l'image, c'est justement la 2e option qui a un gros impact sur le d√©bit.

    Je vais surement investir dans cet √©quipement (j'ai un NAS Syno dont je suis tr√®s content, j'ai envie de continuer avec eux), je te ferais part de mon exp√©rience √† ce moment-l√†.

    En tout cas merci dans pour ton retour!

- id: 22
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2017-11-29 13:27:00
  content: |
    Oui c'est top et √ßa marche vraiment bien. Effectivement le fishing je n'ai pas eu l'occasion de tester, mais pour la publicit√© et le reste c'est devenu la r√®gle par d√©faut sur tous mes appareils.

    Pour la publicit√©, √ßa filtre pas tout, mais une partie seulement. Dans la plupart des cas on peut voir que les js sont bloqu√©s m√™me sans bloqueur de pub sur le navigateur. :)

    Ah oui bien-s√ªr, sur twitter j'ai d√©coch√© les deux cases pour faire des tests mais c'est bien la deuxi√®me qui est probl√©matique, la premi√®re n'a pas d'influence et permet d'avoir un rapport plus complet.

    Oui j'aimerais bien avoir un retour dans le cas d'un g√Æte.

    Merci √† toi !

- id: 23
  author: Yann@44-Atlantique-PC-Assistance-Informatique
  author-url: https://www.44-atlantique-pc.com
  date: 2018-01-19 18:39:45
  content: |
    Article clair m√™me s‚Äôil vaut mieux s‚Äôy connaitre un minimum en r√©seau pour le comprendre! Je r√©alise √† peu pr√®s la m√™me chose avec un routeur Netgear connect√© derri√®re la box, mais suis int√©ress√© par ce routeur Synology... int√©ressant qu‚Äôun DDNS soit propos√©, c‚Äôest dingue qu‚Äôun FAI comme Orange ne le propose toujours pas... √ßa permettrait de pallier aux IP qui ne sont toujours pas fixes (gratuitement) pour les particuliers.

- id: 24
  author: Daniel
  date: 2018-02-28 13:45:23
  content: |
    Bonjour Guillaume,

    Merci pour ce tuto. Je suis dans la m√™me configuration que toi:
    - Livebox pro v4 fibre: quand je suis connect√© dessus en ethernet ou wifi n, un speed test donne 200Mb/s en DOWN et 200Mb/s en UP) -> OK
    - Une fois mon routeur rt1900ac (config basique) branch√© sur la livebox, les d√©bits sont imcompr√©hensibles:
    speed test avec mon pc connect√© en wifi n au RT: 20Mb/s en DOWN et en UP
    speed test avec mon pc connect√© en ethernet (Cat6) au RT: 20Mb/s (environ) en DOWN et 200Mb/s en UP :O

    Si tu as une id√©e, je suis preneur

- id: 25
  author: Guillaume Briday
  author-url: https://guillaumebriday.fr/
  date: 2018-03-04 20:27:00
  content: |
    Bonjour Daniel,

    As-tu regard√© du c√¥t√© des CTF ? J'avais des probl√®mes similaires et √ßa venait de cette config.

    J'en parle dans l'edit 2 si besoin.



